---
output: html_document
---

# Israel

In October of 2018, I had a unique opportunity to visit Israel with Passion City Church. This was a truly eye-opening experience as Israel is unlike any country I have visited before. Israel is the holy land for multiple religions as well as a political battleground. As home to the Dead Sea, a unique place on earth, as well as the Sea of Galilee (pictured), Israel possesses a distinct beauty, whether it be in the lowest place on Earth or the gardens on the Mount of Beatitudes. Israel is a place of multiple cultures and religions, and it is a place where everyone can expand their knowledge and appreciation for other cultures.

# Italy, France, Belgium and Monaco

In September of 2018, I had the opportunity to visit and explore multiple cities in Italy; Nice, France; Brussels, Belgium and Monte Carlo, Monaco. This was an incredible opportunity to visit sites of ancient Roman ruins as well as see modern Italian architecture. Being able to visit foreign countries has shaped who I am as a person as well as given me broader view of the world and the people who live in other countries. Unlike at home, where public transportation is not easily accessible, I was able to use the high-speed trains and visit 11 cities and 5 countries in 10 days. Places like Florence, Venice, Rome, Brussels, Monte Carlo, Pisa, Nice and Milan are cities that can be studied and talked about for years, but pictures and words do them no justice. The picture of the Vatican City on the right does not even touch the beauty of the view nor show the Vatican gardens that were behind me. 

# Peru

During the summers of 2016, 2017 and 2018, I had an incredible opportunity to expand my cultural knowledge by heading to Pucallpa, Peru on two amazing mission trips though Mountain Brook Community Church. Pucallpa, only about an hour's flight away from Lima, or an entire day's bus ride though the Andes Mountains, is a city of around 215,000 people. The city is one of the largest deforestation ports in the Amazon Rainforest due to the location being on the Ucayali River, the major tributary to the Amazon River. During my time in Pucallpa, I helped out on the South American Missions (SAM) base, which houses a school for missionary children as well as three other missionary families. In the mornings we would do light construction, from painting interiors to building exterior walls, followed by a light siesta and then basketball camp for the local kids. Most people would imagine that a city located in the jungle would be primitive in culture, but the children in Pucallpa taught me many life lessons that I would not have learned back in Birmingham.


# Turkey

During my Christmas break sophomore year, I was lucky enough to be able to study abroad in Turkey with a group from Auburn Honors College. This was an incredible experience, because I was able to learn about different cultures in class, and then experience them in person. Being able to stand in the Church of Saint John, pictured above, was one of the coolest things I have ever experienced. I had learned about the events that happened there, and I had seen pictures of it, but nothing compares to actually walking where Saint John walked. I was also able to experience the call to prayer while standing in between the Blue Mosque and the Hagia Sofia, pictured to the left. It was a haunting, unforgettable sound, and it made me stop and reflect on differences, as well as similarities, among people. These experiences will never leave me, and I will always remember how special my study abroad in Turkey was.    

# Greece

During the same study abroad trip as the one to Turkey, I was able to visit Athens and Rhodes, Greece. These two places have an amazing history behind them. Everyone has learned about the ancient ruins in history classes, but few of us have actually seen them in person. Before I left for Athens, I knew a considerable amount of history about the Parthenon, but I never realized how small the actual structure was until I stood beside it. As most people do when visiting historic cities, I went to all the museums, yet the time that affected me the most was when I went with three other members of our group and wandered through the city. We immersed ourselves in the side streets of Athens and discovered food we had never eaten, language we didn’t understand, and people we wish we could see again.   


# Budapest, Hungary

During my sophomore, junior and senior years of high school I was able to go on incredible mission trips to Budapest, Hungary with my youth group. The time I spent in Budapest was exceptional, and working in a central European country changed my life, so much so that I worked, saved, and returned the next summer, and again the next. After each of the three trips, I noticed changes in myself. I became more tolerant, more accepting, and more independent. My faith grew. I learned to laugh at myself and to be flexible. I was humbled by my naivety, and I learned that the world is vast. Yet it was the repetition that changed me the most. Had I gone only once, I certainly would have grown significantly, but I would have missed the benefit of developing long-term, international relationships. I would not have learned that a country, which was over 5,000 miles away and was communist as late as 1990, held people with whom I could develop lasting friendships. I continue these friendships today. 


# Juárez, Mexico

Just across the border from El Paso, Texas, is a town called Juárez. This border town is one of the poorest places in Mexico and continues to grow in size. When I was there, I would stay in an orphanage called Hands of Luke that had been started by Dr. Marco Samaniego in 1988. This ministry has touched more lives than I can imagine, and the three times I was able to help there changed me in many ways. While in Juárez, we spent time in the Colonias, sprawling areas of shacks built of packing crates, cardboard, and sheet metal. We helped any way that we could. My first year we helped roof houses and built a playground out of old tires. During a Thanksgiving break, my family and I went out into the Colonias to serve food. This was eye opening and one of the saddest things I have experienced. But at the same time every single one of the people had high spirits and even put one of their precious jackets on a cold dog. I returned to Juarez once again and was able to contribute more to the community each time, but the violence in the city was escalating, and we were limited. These experiences changed me, and they will be with me for the rest of my life, for they began my desire to learn more about the world.